app/staff/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email, Optional

from app import photos


class AddStaffForm(FlaskForm):
    first_name = StringField("First Name<span class=\"text-danger\">*</span>", validators=[DataRequired()])
    last_name = StringField("Last Name<span class=\"text-danger\">*</span>", validators=[DataRequired()])
    photo = FileField("Photo<span class=\"text-danger\">*</span>", validators=[FileAllowed(photos), FileRequired()])
    role = StringField("Role<span class=\"text-danger\">*</span>", validators=[DataRequired()])
    slack = StringField("Slack ID")
    phone = StringField("Phone")
    email = StringField("Email")
    submit = SubmitField("Add User")

app/watchlist/forms.py
from flask import Markup
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Regexp, ValidationError

from app import photos
from app.models import BannedUser


class BanUserForm(FlaskForm):
    intra_id = StringField(
        "Intra ID<span class=\"text-danger\">*</span>", validators=[
            DataRequired(),
            Regexp(r"^[a-zA-Z-]+$", message="Intra ID supplied contained invalid characters."),
        ]
    )
    photo = FileField("Photo", validators=[FileAllowed(photos)])
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    reason = StringField("Reason<span class=\"text-danger\">*</span>", validators=[DataRequired()])
    submit = SubmitField("Add User")

    def validate_intra_id(self, field):
        if BannedUser.query.filter_by(intra_id=field.data, visible=True).first() is not None:
            raise ValidationError(Markup("<strong>%s</strong> is already on the watchlist." % field.data))

app/staff/__init__.py
from flask import Blueprint

bp = Blueprint("staff", __name__)

from app.staff import routes

app/staff/routes.py
from flask import current_app, flash, jsonify, Markup, redirect, render_template, request, url_for
from flask_login import login_required

import os

from app import db, photos
from app.models import StaffMember
from app.staff import bp
from app.staff.forms import AddStaffForm
from app.util import hash_rename


@bp.route("/")
@login_required
def stafflist():
    return render_template(
        "lists/staff.html",
        staff_members=StaffMember.query.filter_by(visible=True), form=AddStaffForm(), photos=photos, title="Staff"
    )


@bp.route("/add", methods=["POST"])
@login_required
def add_to_staff():
    form = AddStaffForm()
    if not form.validate_on_submit():
        for _, errors in form.errors.items():
            for msg in errors:
                flash(msg, "danger")
        return redirect(url_for(".stafflist"))

    photo_name = hash_rename(photos, photos.save(form.photo.data))
    sm = StaffMember(
        first_name=form.first_name.data,
        last_name=form.last_name.data,
        photo=photo_name,
        role=form.role.data,
        slack=form.slack.data,
        phone=form.phone.data,
        email=form.email.data
    )
    db.session.add(sm)
    db.session.commit()
    flash(Markup("<strong>%s %s</strong> has been added to staff." % (sm.first_name, sm.last_name)), "success")
    return redirect(url_for(".stafflist"))


@bp.route("/remove/<id>")
@login_required
def remove_from_staff(id):
    sm = StaffMember.query.filter_by(id=id).first()

    if sm is not None:
        sm.visible = False
        db.session.commit()
        flash(Markup("<strong>%s %s</strong> has been removed from staff." % (sm.first_name, sm.last_name)), "success")
    else:
        flash("User specified could not be found.", "danger")

    return redirect(url_for(".stafflist"))


@bp.route("/edit/firstName", methods=["POST"])
@login_required
def edit_first_name():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.first_name = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/lastName", methods=["POST"])
@login_required
def edit_last_name():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.last_name = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/role", methods=["POST"])
@login_required
def edit_role():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.role = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/slack", methods=["POST"])
@login_required
def edit_slack():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.slack = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/phone", methods=["POST"])
@login_required
def edit_phone():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.phone = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/email", methods=["POST"])
@login_required
def edit_email():
    sm = StaffMember.query.filter_by(id=request.form.get("pk")).first()
    sm.email = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)

app/watchlist/__init__.py
from flask import Blueprint

bp = Blueprint("watchlist", __name__)

from app.watchlist import routes

app/watchlist/routes.py
from flask import flash, jsonify, Markup, redirect, render_template, request, url_for
from flask_login import login_required

from app import db, photos
from app.intra import get_user_info
from app.models import BannedUser
from app.util import hash_rename
from app.watchlist import bp
from app.watchlist.forms import BanUserForm


@bp.route("/")
@login_required
def watchlist():
    return render_template(
        "lists/watchlist.html",
        banned=BannedUser.query.filter_by(visible=True), form=BanUserForm(), photos=photos, title="Watchlist"
    )


@bp.route("/add", methods=["POST"])
@login_required
def add_to_watchlist():
    form = BanUserForm()
    if not form.validate_on_submit():
        for _, errors in form.errors.items():
            for msg in errors:
                flash(msg, "danger")
        return redirect(url_for(".watchlist"))

    intra_id = form.intra_id.data
    user_info = None

    if form.photo.has_file():
        photo_name = photos.save(form.photo.data)
    else:
        user_info = get_user_info(intra_id, save_photo=True)
        photo_name = None if user_info is None else user_info.get("photo_name")

    if photo_name is not None:
        photo_name = hash_rename(photos, photo_name)

    no_first = len(form.first_name.data) == 0
    no_last = len(form.last_name.data) == 0

    if user_info is None and (no_first or no_last):
        user_info = get_user_info(intra_id, save_photo=False)
        if user_info is None:
            flash(Markup(
                "Unable to find intra user <strong>%s</strong>. "
                "First and last name must be specified." % intra_id
            ), "danger")
            return redirect(url_for(".watchlist"))

    bu = BannedUser(
        intra_id=intra_id,
        first_name=user_info.get("first_name") if no_first else form.first_name.data,
        last_name=user_info.get("last_name") if no_last else form.last_name.data,
        reason=form.reason.data,
        photo=photo_name
    )
    db.session.add(bu)
    db.session.commit()
    flash(Markup("<strong>%s</strong> has been added to the watchlist." % intra_id), "success")
    return redirect(url_for(".watchlist"))


@bp.route("/remove/<id>")
@login_required
def remove_from_watchlist(id):
    bu = BannedUser.query.filter_by(id=id).first()

    if bu is not None:
        bu.visible = False
        db.session.commit()
        flash(Markup("<strong>%s</strong> has been removed from the watchlist." % bu.intra_id), "success")
    else:
        flash(Markup("<strong>%s</strong> is not on the watchlist." % bu.intra_id), "danger")

    return redirect(url_for(".watchlist"))


@bp.route("/edit/firstName", methods=["POST"])
@login_required
def edit_first_name():
    bu = BannedUser.query.filter_by(id=request.form.get("pk")).first()
    bu.first_name = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/lastName", methods=["POST"])
@login_required
def edit_last_name():
    bu = BannedUser.query.filter_by(id=request.form.get("pk")).first()
    bu.last_name = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)


@bp.route("/edit/reason", methods=["POST"])
@login_required
def edit_reason():
    bu = BannedUser.query.filter_by(id=request.form.get("pk")).first()
    bu.reason = request.form.get("value")
    db.session.commit()
    return jsonify(success=True)

app/templates/lists/list_base.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles_extra %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"
          integrity="sha384-1UXhfqyOyO+W+XsGhiIFwwD3hsaHRz2XDGMle3b8bXPH5+cMsXVShDoHA3AH/y/p"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css"
          integrity="sha384-EkHEUZ6lErauT712zSr0DZ2uuCmi3DoQj6ecNdHQXpMpFNGAQ48WjfXCE5n20W+R"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css"/>
    <style>
        .back-to-top {
            cursor: pointer;
            position: fixed;
            bottom: 20px;
            right: 20px;
            display: none;
            z-index: 9001;
        }

        .list-container {
            width: 100%;
        }

        table.dataTable tbody td {
            vertical-align: middle;
        }

        .panel-heading a:after {
            font-family: 'Glyphicons Halflings';
            content: "\e114";
            float: right;
            color: grey;
        }

        .panel-heading a.collapsed:after {
            content: "\e080";
        }

        .popover-img {
            width: 100%;
        }

        .popover {
            max-width: 50%;
        }

        .popover .arrow {
            display: none;
        }
    </style>
{% endblock %}

{% block scripts_extra %}
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
            integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp"
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    {{ moment.include_moment() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#list").DataTable({
                "order": [
                    [5, "desc"]
                ],
                "columnDefs": [
                    {
                        "targets": "no-sort",
                        "orderable": false,
                    },
                    {
                        "targets": "no-search",
                        "searchable": false,
                    },
                    {
                        "type": "date-us",
                        "targets": 5,
                    },
                ],
                "fnRowCallback": function () {
                    $(".editable").editable({
                        "send": "always",
                        "type": "text",
                        "validate": function (value) {
                            if (value === "") {
                                return "Must not be blank";
                            }
                        },
                    });

                    $(".editable-empty").editable({
                        "emptytext": "N/A",
                        "send": "always",
                        "type": "text",
                    });
                }
            });
        });

        $(".confirm-delete").on("click", function () {
            return confirm("Remove '" + $(this).data("user") + "' from list?");
        });

        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) {
                $('#back-to-top').fadeIn();
            } else {
                $('#back-to-top').fadeOut();
            }
        });

        $('#back-to-top').click(function () {
            $('#back-to-top').tooltip('hide');
            $('body,html').animate({
                scrollTop: 0
            }, 800);
            return false;
        });

        $('#back-to-top').tooltip('show');

        $('[data-toggle="popover"]').popover({
            "html": true,
            "trigger": "hover",
            "content": function () {
                return '<img class="popover-img" src="' + $(this).data("img") + '" />';
            },
        });
    </script>
{% endblock %}

{% block app_content %}
    <h1>{% block page_title %}{% endblock %}</h1>
    <table class="list-container">
        <tr>
            <td>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-target="#list-collapse" href="#list-collapse">
                                {% block table_title %}{% endblock %}
                            </a>
                        </h4>
                    </div>
                    <div id="list-collapse" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table id="list" class="table table-striped table-bordered">
                                {% block table_data %}{% endblock %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-target="#list-add-collapse"
                                       href="#list-add-collapse">
                                        {% block form_title %}{% endblock %}
                                    </a>
                                </h4>
                            </div>
                            <div id="list-add-collapse" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    {% block form_content %}{% endblock %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    </table>
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button"
       title="Back to top" data-toggle="tooltip" data-placement="left"><span
            class="glyphicon glyphicon-chevron-up"></span></a>
{% endblock %}

app/templates/lists/staff.html
{% extends "lists/list_base.html" %}

{% block page_title %}Staff{% endblock %}

{% block table_title %}Staff Members{% endblock %}

{% block table_data %}
    <thead>
    <tr>
        <th class="no-sort no-search">Photo</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Role</th>
        <th class="no-sort">Contact</th>
        <th>Added</th>
        <th class="no-sort no-search"></th>
    </tr>
    </thead>
    <tbody>
    {% for sm in staff_members %}
        <tr>
            <td class="text-center">
                <a href="#" data-toggle="popover" data-img="{{ photos.url(sm.photo or "unknown.png") }}">
                    <img alt="{{ sm.first_name }}" src="{{ photos.url(sm.photo or "unknown.png") }}?thumb=True">
                </a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ sm.id }}"
                   data-url="{{ url_for("staff.edit_first_name") }}"
                   data-title="First Name">{{ sm.first_name }}</a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ sm.id }}"
                   data-url="{{ url_for("staff.edit_last_name") }}"
                   data-title="Last Name">{{ sm.last_name }}</a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ sm.id }}"
                   data-url="{{ url_for("staff.edit_role") }}"
                   data-title="Role">{{ sm.role }}</a>
            </td>
            <td>
                <p class="text-nowrap">
                    <span class="glyphicon glyphicon-comment"></span>
                    <a href="#" class="editable-empty" data-pk="{{ sm.id }}"
                       data-url="{{ url_for("staff.edit_slack") }}"
                       data-title="Slack ID">{{ sm.slack }}</a>
                </p>
                <p class="text-nowrap">
                    <span class="glyphicon glyphicon-phone-alt"></span>
                    <a href="#" class="editable-empty" data-pk="{{ sm.id }}"
                       data-url="{{ url_for("staff.edit_phone") }}"
                       data-title="Phone Number">{{ sm.phone }}</a>
                </p>
                <p class="text-nowrap">
                    <span class="glyphicon glyphicon-envelope"></span>
                    <a href="#" class="editable-empty" data-pk="{{ sm.id }}"
                       data-url="{{ url_for("staff.edit_email") }}"
                       data-title="Email">{{ sm.email }}</a>
                </p>
            </td>
            <td>{{ moment(sm.timestamp).fromNow() }}</td>
            <td class="text-center">
                <a class="btn btn-danger confirm-delete"
                   href="{{ url_for("staff.remove_from_staff", id=sm.id) }}"
                   data-user="{{ sm.first_name }}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

{% block form_title %}Add to Staff{% endblock %}

{% block form_content %}
    {{ wtf.quick_form(form, action=url_for("staff.add_to_staff"), button_map={"submit":"primary"}) }}
{% endblock %}

app/templates/lists/watchlist.html
{% extends "lists/list_base.html" %}

{% block page_title %}Watchlist{% endblock %}

{% block table_title %}Banned Users{% endblock %}

{% block table_data %}
    <thead>
    <tr>
        <th class="no-sort no-search">Photo</th>
        <th>Intra ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th class="no-sort">Reason</th>
        <th class="no-search">Added</th>
        <th class="no-sort no-search"></th>
    </tr>
    </thead>
    <tbody>
    {% for bu in banned %}
        <tr>
            <td class="text-center">
                <a href="#" data-toggle="popover" data-img="{{ photos.url(bu.photo or "unknown.png") }}">
                    <img alt="{{ bu.intra_id }}" src="{{ photos.url(bu.photo or "unknown.png") }}?thumb=True">
                </a>
            </td>
            <td>
                <a target="_blank" href="https://profile.intra.42.fr/users/{{ bu.intra_id }}">{{ bu.intra_id }}</a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ bu.id }}"
                   data-url="{{ url_for("watchlist.edit_first_name") }}"
                   data-title="First Name">{{ bu.first_name }}</a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ bu.id }}"
                   data-url="{{ url_for("watchlist.edit_last_name") }}"
                   data-title="Last Name">{{ bu.last_name }}</a>
            </td>
            <td>
                <a href="#" class="editable" data-pk="{{ bu.id }}"
                   data-url="{{ url_for("watchlist.edit_reason") }}"
                   data-title="Reason">{{ bu.reason }}</a>
            </td>
            <td>{{ moment(bu.timestamp).fromNow() }}</td>
            <td class="text-center">
                <a class="btn btn-danger confirm-delete"
                   data-user="{{ bu.intra_id }}"
                   href="{{ url_for("watchlist.remove_from_watchlist", id=bu.id) }}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

{% block form_title %}Add to Watchlist{% endblock %}

{% block form_content %}
    {{ wtf.quick_form(form, action=url_for("watchlist.add_to_watchlist"), button_map={"submit":"primary"}) }}
{% endblock %}